import { ReactElement, useCallback, useEffect } from "react";
import { getRPGMaker } from "../../../rpgmaker";
import { ICheatModuleProps } from "../declare";
import styles from "./style.module.scss";

export const WarningMessage =
  "Generated saving file CANNOT be loaded by Game directly, " +
  "you have to rename the saving file to an existing saving file which was generated by the Game.";

export default function InfiniteSave({
  onScriptChange,
}: ICheatModuleProps): ReactElement {
  const make = useCallback(() => {
    return getRPGMaker().getScriptGenerator().saveGameWithTimestampAsName();
  }, []);

  const run = useCallback(() => {
    getRPGMaker().evaluate(make());
  }, [make]);

  useEffect(() => {
    return () => {
      onScriptChange?.(make());
    };
  }, [make, onScriptChange]);

  return (
    <div className={styles.wrapper}>
      <div>⚠️ ⚠️ ⚠️</div>
      <div>{WarningMessage}</div>
      <button onClick={run}>Save Now</button>
    </div>
  );
}
